### ISSUE TITLE
Torchpoints error during running colab.

### ISSUE THREAD

**Issue by chenerg** [humanpose1/MS-SVConv#6]
![image](https://user-images.githubusercontent.com/24982715/129662209-451eb4ef-77ee-4760-872b-74d01aa28940.png)

INFO - 2021-08-17 04:07:39,444 - model_checkpoint - Loading checkpoint from models/MS_SVCONV_2cm_X2_3head_3dm.pt
INFO - 2021-08-17 04:07:39,799 - modelfactory - The config will be used to build the model
invalid syntax (<string>, line 1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-6582ff1e3e11> in <module>()
     19 }
     20 
---> 21 model = PretainedRegistry.from_file(pcd_model[choice_model], mock_property={})
     22 
     23 data_s = pcd_DA[choice_model](read_pcd(pcd_path[choice_data][0]))

13 frames
/usr/local/lib/python3.7/dist-packages/torch_points3d/modules/SparseConv3d/nn/torchsparse.py in __init__(self, in_channels, out_channels, kernel_size, stride, dilation, bias, transpose)
     37             dilation=dilation,
     38             bias=bias,
---> 39             transposed=True,
     40         )
     41 

TypeError: __init__() got an unexpected keyword argument 'transposed'

**Comment by humanpose1** [comment]
Thanks for reporting it.Now tp3d works with torchsparse 1.4.0 version. I'll fix it asap.
Best,

**Comment by humanpose1** [comment]
Error fixed !
